### ISSUE TITLE
Is any modification in mmdetection3d?

### ISSUE THREAD

**Issue by YexingWan** [hustvl/MapTR#10]
Thanks for the gorgeous work! I see a full mmdetection3d project is included. Is any difference or code modification with the origin open source version? 
Thank you.

**Comment by LegendBC** [comment]
It should be fine to perform the experiments with the original open-source mmdetection3d. Our provided mmdetection3d is slightly different from the original, we integrate some features of [BEVFusion](https://github.com/mit-han-lab/bevfusion) to ablate 2d-to-bev transformation module with optimized LSS-style bevpool in Table 3 of our [paper](https://arxiv.org/abs/2208.14437) and support multi-modality settings in MapTR, which will be released in the future.

**Comment by YexingWan** [comment]
Thanks for your reply. :dango: 
So if i only play with GKT, it's fine to install original open-source v0.17.1 mmdetection3d. 

Moreover, the implementation of GKT is different from original [GKT](https://github.com/hustvl/GKT/tree/main/segmentation/cross_view_transformer/model) which seems to implement a cuda version GKA module in this project. For reproducing the FPS, Is it necessary to use the cuda kernel GKA instead the torch version when do infer?

**Comment by LegendBC** [comment]
> For reproducing the FPS, Is it necessary to use the cuda kernel GKA instead the torch version when do infer?

Yes, the FPS is tested with GKT's cuda kernel

**Comment by YongtaoGe** [comment]
> It should be fine to perform the experiments with the original open-source v0.17.1 mmdetection3d . Our provided mmdetection3d is slightly different from the original, we integrate some features of [BEVFusion](https://github.com/mit-han-lab/bevfusion) to ablate 2d-to-bev transformation module with optimized LSS-style bevpool in Table 3 of our [paper](https://arxiv.org/abs/2208.14437) and support multi-modality settings in MapTR, which will be released in the future.

Hi, thanks for your great work. Can you provide a config file for the LSS-style MapTR?
