### ISSUE TITLE
Fail in Model Evaluation

### ISSUE THREAD

**Issue by Jasonliuzhecheng** [hustvl/MapTR#11]
When I want to reproduce this work, I fail to evaluate the model that I've trained.

The problem happens at:
https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/datasets/map_utils/tpfp_chamfer.py#L48

The STRTree function query output is ndarry, the tree geometry indices, which cannot intersects.
Hope to fix this problem.

**Comment by LegendBC** [comment]
> I fail to evaluate the model that I've trained.

Can you evaluate the model we provide?

**Comment by Jasonliuzhecheng** [comment]
Same problem happens. As I said, this is an evaluation problem, but not model infer problem. Thus nothing related with model itself.

**Comment by LegendBC** [comment]
Can you report your detailed log and environmental setting, especially your `shapely` version, to help us reproduce your problem?

**Comment by Jasonliuzhecheng** [comment]
detailed log:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "git/MapTR/projects/mmdet3d_plugin/datasets/map_utils/tpfp.py", line 57, in custom_tpfp_gen
    matrix = custom_polyline_score(
  File "git/MapTR/projects/mmdet3d_plugin/datasets/map_utils/tpfp_chamfer.py", line 49, in custom_polyline_score
    if o.intersects(pline):
AttributeError: 'numpy.int64' object has no attribute 'intersects'

shapely version: 2.0b2

**Comment by LegendBC** [comment]
You may try `shapely` in 1.8.5.post1 version. This should work fine.
