### ISSUE TITLE
关于如何使用提供的权重推理？

### ISSUE THREAD

**Issue by Zhutianyi7230** [hustvl/MapTR#15]
感谢作者开源这一非常优秀的工作！
我想要使用您提供的训练好的权重进行推理，复现一个demo，
也就是`path/to/MapTR/tools/maptr`中的一些程序（vis_pred.py等），请问具体该如何使用呢（用什么命令参数，各个文件的摆放位置等）？
感谢您的交流！

**Comment by cyn-liu** [comment]
@Zhutianyi7230 我也使用作者提供的模型进行推理，但是如何对推理结果进行可视化，请问你有进展吗？
感谢交流！

**Comment by Zhutianyi7230** [comment]
@cyn-liu 我暂时还没有推理，按作者所说推理和可视化代码应该都在path/to/MapTR/tools/maptr中，我还不知道如何使用，如果您能跑通推理流程的话可以告诉我一下大致如何操作吗，谢谢！

**Comment by cyn-liu** [comment]
@Zhutianyi7230 推理作者在这里写了说明：https://github.com/hustvl/MapTR/blob/main/docs/train_eval.md
，使用./tools/dist_test_map.sh ./projects/configs/maptr/maptr_tiny_r50_24e.py ./path/to/ckpts.pth 8这条指令后，会在test文件夹下生成.json文件等，但是我不清楚用哪个文件可视化，以及如何设置参数等。

**Comment by Zhutianyi7230** [comment]
@cyn-liu 我认为./tools/dist_test_map.sh这个应该是在数据集上验证用的。想要用权重直接推理的话可以看一下/tools/maptr/vis_pred.py这个代码，我还没仔细看过，但是它里面有plt函数，按该代码要求设置参数，应该可以可视化。

**Comment by cyn-liu** [comment]
@Zhutianyi7230 推理需要数据，用数据集的数据并没有什么问题，问题是使用dist_test_map.sh推理后生成的文件如何可视化呢？

可能使用vis_pred.py也可以推理，但是我在这个文件中并没有看到如何设置推理数据的地方。

**Comment by cyn-liu** [comment]
@Zhutianyi7230 我使用/tool/maptr/vis_pred.py这个脚本可视化推理结果是成功了的，这个脚本可视化的是整个测试集。

**Comment by LegendBC** [comment]
可视化脚本使用： python ./tool/maptr/vis_pred.py /path/to/config /path/to/ckpt --gt-format fixed_num_pts polyline_pts --score-thresh 0.4。摆放位置就follow教程就好，可视化的脚本不需要专门设置路径，通过读取config会自动设置好这些
