### ISSUE TITLE
ModuleNotFoundError: No module named 'projects'

### ISSUE THREAD

**Issue by BatyrM** [hustvl/MapTR#180]
When training the model, gives the following error: ModuleNotFoundError: No module named 'projects'

![Screenshot from 2024-08-01 15-39-48](https://github.com/user-attachments/assets/a40116ed-7d5c-4ce6-afc5-2a6ebf86b509)

**Comment by Kerwin0621** [comment]
import sys
sys.path.insert(0, './MapTR')
If not working, try the absolute path

**Comment by BatyrM** [comment]
Thank you! I will try.

**Comment by BatyrM** [comment]
Writing the absolute path helped. Thank you @Kerwin0621!
