### ISSUE TITLE
how can we get the ground-truth map?

### ISSUE THREAD

**Issue by Kitem** [hustvl/MapTR#2]

**Comment by LegendBC** [comment]
We extract the ground-truth map elements following [HDMapNet](https://github.com/Tsinghua-MARS-Lab/HDMapNet). Recently, I am cleaning the code, and we'll release it as soon as possible.

**Comment by LegendBC** [comment]
We release an initial version of MapTR, you can refer to the code for more details, so I'm closing this issue, but let us know if you have further questions.
