### ISSUE TITLE
visualization question 

### ISSUE THREAD

**Issue by ygjwd12345** [hustvl/MapTR#26]
There are a few style gt formats for vis in tools/maptr, such as "fixed_num_pts", 'fixed_num_pts_torch', "polyline_pts",'polyline_pts_quiver','polyline_dilated_pts', 'shift_fixed_num_pts'，'shift_fixed_num_pts_v1...3'.
would you mind to tell which one is the default?

**Comment by LegendBC** [comment]
Hi @ygjwd12345  thanks for your interest! You can use multiple visualization formats in the command. In the paper, we use "fixed_num_pts", which interpolates the original "polyline_pts" format GT with fixed num points.

**Comment by ygjwd12345** [comment]
@LegendBC  Thanks a lot
