### ISSUE TITLE
reproduce 2D-to-BEV transformation

### ISSUE THREAD

**Issue by zen-d** [hustvl/MapTR#29]
@LegendBC Thanks for your great work! 

Would you mind also releasing your implementation of other 2D-to-BEV transformations used for ablation in Table 3? Because I would like to check the details and make a fair comparison of this component on other hardware platforms like what you have done. Thanks.

**Comment by LegendBC** [comment]
We do not plan to release this part of the code now,  since it will break the code structure, and the 2D-to-BEV transformations are not our contribution. We may release it after we open-source the parts stated in https://github.com/hustvl/MapTR/tree/main/tools/maptr

**Comment by SuperPengXue** [comment]
> We do not plan to release this part of the code now, since it will break the code structure, and the 2D-to-BEV transformations are not our core contribution. We may release it after we open-source the parts stated in https://github.com/hustvl/MapTR#catalog
@LegendBC   amazing, thanks for your great work!!!, 
Everyone is also very concerned about the implementation of these different methods  in Table 3 , it is really exciting！

**Comment by LegendBC** [comment]
I have updated the transformation parts. So I close this issue.
