### ISSUE TITLE
Codes for visualization

### ISSUE THREAD

**Issue by ZhangGongjie** [hustvl/MapTR#35]
Thanks for the awesome work! 

I just wish to ask whether you could share the codes for map visualization for GT and predictions.

Thanks in advance.

**Comment by LegendBC** [comment]
We have open-sourced all visualization code [here](https://github.com/hustvl/MapTR/tree/main/tools/maptr). We are busy on another DDL and will add visualization documentation in two weeks.

**Comment by ZhangGongjie** [comment]
Thanks! Good luck with your ICCV submission!

**Comment by ZhangGongjie** [comment]
2023-03-10 10:18:52,706 - mmdet3d - ERROR - WRONG visformat for GT: se_points

**Comment by LegendBC** [comment]
Hi @ZhangGongjie , we update the visualization code and document. You can update and try it again~

**Comment by ZhangGongjie** [comment]
Deeply appreciated!
