### ISSUE TITLE
Validation set

### ISSUE THREAD

**Issue by TonyXuQAQ** [hustvl/MapTR#37]
Hi there. In your repo, the validation set is the same as the testing set. Is this the normal case for Nuscenes in the computer vision community?

**Comment by LegendBC** [comment]
We follow the dataset split setting of HDMapNet and VectorMapNet for a fair comparison. Since we only train on the nuScenes train set. The test result on the validation set should be enough.

**Comment by TonyXuQAQ** [comment]
Thanks for the declaration.
