### ISSUE TITLE
loss bbox and loss iou？

### ISSUE THREAD

**Issue by czy341181** [hustvl/MapTR#41]
Hi， Bencheng， awesome work！ Congratulation！ 

I found that loss bbox and loss iou weights have been set to 0 in the matching cost and calculation loss. Is there any improvement after adding them?

**Comment by czy341181** [comment]
https://github.com/hustvl/MapTR/blob/98a92ce97cec6128e2693d5395580727a639ff6c/projects/configs/maptr/maptr_nano_r18_110e.py#L187

**Comment by LegendBC** [comment]
Hi @czy341181 , thanks for your interest! We have not observed any improvement after adding them in our own experiments.
