### ISSUE TITLE
Visualize Prediction Failure following the docs

### ISSUE THREAD

**Issue by wbjsamuel** [hustvl/MapTR#42]
Hi, thanks for the nice work! I strictly followed the docs you provided and completed the part of training and evaluation(`maptr_tiny_r50_24e.py`). However, when I want to visualize the prediction, I meet this problem 
```shell
Traceback (most recent call last):
  File "tools/maptr/vis_pred.py", line 401, in <module>
    main()
  File "tools/maptr/vis_pred.py", line 235, in main
    pts_filename = img_metas[0]['pts_filename']
KeyError: 'pts_filename'
```
It seems to be caused by something with the data. Could you please tell me how can I modify the raw code to get it right? Thanks a lot.

**Comment by LegendBC** [comment]
I have fixed this problem, you can pull the repo and try it again. It is due to the [modification](https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_map_dataset.py#L1116-L1117) of supporting the multi-modality

**Comment by wbjsamuel** [comment]
> I have fixed this problem, you can pull the repo and try it again. It is due to the [modification](https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_map_dataset.py#L1116-L1117) of supporting the multi-modality

Thanks for the update! The visualization problem has been settled!
