### ISSUE TITLE
`ann_file` vs `map_ann_file` in config file

### ISSUE THREAD

**Issue by quangnhat185** [hustvl/MapTR#47]
Dear, 
First of all I would like to express my admiration about the good work you have here.

I have a question regarding the parameters `ann_file` and `map_ann` from your the config file:
```python
ann_file=ann_file + 'nuscenes_infos_temporal_val.pkl',
map_ann_file=data_root + 'nuscenes_map_anns_val.json', 
```

I understood that the `ann_file` is the path to the annotation file which is created using your `create_data.py` script. However I don't know where `map_ann_file` come from? Could you please elaborate this parameter?

**Comment by LegendBC** [comment]
The map_ann_file is generated on the fly to adapt the customized setting of different range here https://github.com/hustvl/MapTR/blob/476a39bc0e/projects/mmdet3d_plugin/datasets/nuscenes_map_dataset.py#L1246-L1283

**Comment by quangnhat185** [comment]
Thank you for your answer 👍
