### ISSUE TITLE
Hierarchical matching question

### ISSUE THREAD

**Issue by czy341181** [hustvl/MapTR#50]
Hi, bencheng, thanks for your great work.
My question is about Hierarchical matching.

In your paper, first perform instance level matching to find the corresponding lane lines, and then perform point-level matching to find the internal points of each lane line. 
Is my understanding correct?

if so, I think there should be two Hungarian matching processes.
But I don't find the corresponding code. It seems like there is only one matching process, which is different from that described in the paper?
https://github.com/hustvl/MapTR/blob/476a39bc0e6345d803b797d73db35ee6235f50cd/projects/mmdet3d_plugin/maptr/assigners/maptr_assigner.py#L182

https://github.com/hustvl/MapTR/blob/476a39bc0e6345d803b797d73db35ee6235f50cd/projects/mmdet3d_plugin/maptr/assigners/maptr_assigner.py#L170

**Comment by cvchanghao** [comment]
same questions.
I also wonder which piece of code is the gt generation？ the permutation of points

**Comment by czy341181** [comment]
the permutation of points is here:

https://github.com/hustvl/MapTR/blob/67aeb63fc11e18075232a5cf9455cc7878284970/projects/mmdet3d_plugin/datasets/nuscenes_map_dataset.py#L290

https://github.com/hustvl/MapTR/blob/67aeb63fc11e18075232a5cf9455cc7878284970/projects/mmdet3d_plugin/maptr/dense_heads/maptr_head.py#L670

**Comment by LegendBC** [comment]
> Hi, bencheng, thanks for your great work. My question is about Hierarchical matching.
> 
> In your paper, first perform instance level matching to find the corresponding lane lines, and then perform point-level matching to find the internal points of each lane line. Is my understanding correct?
> 
> if so, I think there should be two Hungarian matching processes. But I don't find the corresponding code. It seems like there is only one matching process, which is different from that described in the paper?
> 
> https://github.com/hustvl/MapTR/blob/476a39bc0e6345d803b797d73db35ee6235f50cd/projects/mmdet3d_plugin/maptr/assigners/maptr_assigner.py#L182
> 
> https://github.com/hustvl/MapTR/blob/476a39bc0e6345d803b797d73db35ee6235f50cd/projects/mmdet3d_plugin/maptr/assigners/maptr_assigner.py#L170


sorry for late reply, `linear_sum_assignment` is instance level hungarian match, `torch.min` is the permutation level min match, and we  get the assigned permutation here https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/maptr/dense_heads/maptr_head.py#L410
