### ISSUE TITLE
请问网络权重和数据集会开源吗？

### ISSUE THREAD

**Issue by wo712268** [hustvl/MapTR#6]
你好！我正在做高精地图语义识别的课题，看到这篇文章，发现其中的语义内容比我们目前做的要更丰富一些，有道路标志。请问网络权重，或者是你们用于训练的数据集会开源吗？救救学生，谢谢了%>_<%

**Comment by LegendBC** [comment]
你好，我们是基于开源数据集[NuScenes](https://www.nuscenes.org/)进行训练，网络权重后面会进行开源，请保持关注。

**Comment by jinfagang** [comment]
@LegendBC Hi，NuScenes有这个GT标注吗？那是不是可以把这个boundary和detection联合起来一起训

**Comment by LegendBC** [comment]
@jinfagang 是的，NuScenes提供了动态物体和静态高精度地图的标注。

**Comment by LegendBC** [comment]
We release an initial version of MapTR, I'm closing this issue, but let us know if you have further questions.
