### ISSUE TITLE
argoverse2 line_divider processing

### ISSUE THREAD

**Issue by PeggyPeppa** [hustvl/MapTR#61]
Hi~ After reading the av2converter.py, it seems not deal with this situation: A line_divider between two adjacent lanes, it was calculated twice in your code not filtered into single one. Will this affect the effect on argoverse2 dataset?

**Comment by 123Vincent2018** [comment]
it looks like no enough support for processing the  argoverse2 datasets and training task.

**Comment by PeggyPeppa** [comment]
Actually in Shapely "ops.unary_union" and "ops.linemerge"provide this fuction.  It was also provided in author‘s code. Thanks!
