### ISSUE TITLE
Was result['scores_3d'] used to filter the raw bounding box prediction before calculating the chamfer distance metric?

### ISSUE THREAD

**Issue by mimichu** [hustvl/MapTR#64]
Thanks for the great work and sharing the code!

Curious whether the ` scores_3d ` used in [visualization](https://github.com/hustvl/MapTR/blob/main/tools/maptr/vis_pred.py#L354) is also used in calculating the chamfer/iou metric, and if so, how was it used? For example, was the ` scores_3d `  used to help generate the `gen_lines` before calculating the chamfer metric as shown [here](https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/datasets/map_utils/tpfp.py#LL9C7-L9C7)?

Thanks!

**Comment by LegendBC** [comment]
Thanks for your interest! The last dim of [`gen_lines`](https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/datasets/map_utils/tpfp.py#L54) is the score of each line.

**Comment by mimichu** [comment]
Got it! Thanks for the pointer!

**Comment by mimichu** [comment]
Got it! Thanks for the pointer!
