### ISSUE TITLE
Bug when using queue_length >1

### ISSUE THREAD

**Issue by swc-17** [hustvl/MapTR#68]
Hi,
I found that using queue_length > 1 will cause problem, it seems that after adding lidar branch, the function argument at https://github.com/hustvl/MapTR/blob/6de488105b58da0d27b153ade468ef18653a277d/projects/mmdet3d_plugin/maptr/detectors/maptr.py#L181C27-L181C27 is not updated.
After fixing above bug, another arises:
`Parameters which did not receive grad for rank 3: img_neck.fpn_convs.0.conv.bias, img_neck.fpn_convs.0.conv.weight, img_neck.lateral_convs.0.conv.bias, img_neck.lateral_convs.0.conv.weight, img_backbone.layer4.2.conv3.weight, img_backbone.layer4.2.conv2.weight, img_backbone.layer4.2.conv1.weight, img_backbone.layer4.1.conv3.weight, img_backbone.layer4.1.conv2.weight, img_backbone.layer4.1.conv1.weight, img_backbone.layer4.0.downsample.0.weight, img_backbone.layer4.0.conv3.weight, img_backbone.layer4.0.conv2.weight, img_backbone.layer4.0.conv1.weight, img_backbone.layer3.5.conv3.weight, img_backbone.layer3.5.conv2.weight, img_backbone.layer3.5.conv1.weight, img_backbone.layer3.4.conv3.weight, img_backbone.layer3.4.conv2.weight, img_backbone.layer3.4.conv1.weight, img_backbone.layer3.3.conv3.weight, img_backbone.layer3.3.conv2.weight, img_backbone.layer3.3.conv1.weight, img_backbone.layer3.2.conv3.weight, img_backbone.layer3.2.conv2.weight, img_backbone.layer3.2.conv1.weight, img_backbone.layer3.1.conv3.weight, img_backbone.layer3.1.conv2.weight, img_backbone.layer3.1.conv1.weight, img_backbone.layer3.0.downsample.0.weight, img_backbone.layer3.0.conv3.weight, img_backbone.layer3.0.conv2.weight, img_backbone.layer3.0.conv1.weight, img_backbone.layer2.3.conv3.weight, img_backbone.layer2.3.conv2.weight, img_backbone.layer2.3.conv1.weight, img_backbone.layer2.2.conv3.weight, img_backbone.layer2.2.conv2.weight, img_backbone.layer2.2.conv1.weight, img_backbone.layer2.1.conv3.weight, img_backbone.layer2.1.conv2.weight, img_backbone.layer2.1.conv1.weight, img_backbone.layer2.0.downsample.0.weight, img_backbone.layer2.0.conv3.weight, img_backbone.layer2.0.conv2.weight, img_backbone.layer2.0.conv1.weight, pts_bbox_head.transformer.encoder.layers.0.ffns.0.layers.1.bias, pts_bbox_head.transformer.encoder.layers.0.ffns.0.layers.1.weight, pts_bbox_head.transformer.encoder.layers.0.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.encoder.layers.0.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.encoder.layers.0.attentions.0.sampling_offsets.weight, pts_bbox_head.transformer.encoder.layers.0.attentions.0.sampling_offsets.bias, pts_bbox_head.transformer.encoder.layers.0.attentions.0.attention_weights.weight, pts_bbox_head.transformer.encoder.layers.0.attentions.0.attention_weights.bias, pts_bbox_head.transformer.encoder.layers.0.attentions.0.value_proj.weight, pts_bbox_head.transformer.encoder.layers.0.attentions.0.value_proj.bias, pts_bbox_head.transformer.encoder.layers.0.attentions.0.output_proj.weight, pts_bbox_head.transformer.encoder.layers.0.attentions.0.output_proj.bias
Parameter indices which did not receive grad for rank 3: 4 5 6 7 8 9 10 11 18 19 20 21 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312`

But running bevformer with queue_length >1 have no problem, any idea about solution?
Thanks!

**Comment by LegendBC** [comment]
Thanks for your interest! Currently, this repo does not support the temporal setting. We will add this feature in the near future.

**Comment by LegendBC** [comment]
We have supported the temporal feature in the latest MapTRv1 code. So I'm closing this issue.
