### ISSUE TITLE
关于av2模块不存在的问题

### ISSUE THREAD

**Issue by handsomeZhuang** [hustvl/MapTR#75]
您好，非常感谢优秀的作品开源！
当使用maptr_tiny_r50_110e.pth直接进行test时，提示av2模块不存在，另外也无法通过av2_converter.py生成av2数据，请问：av2模块怎么生成？

**Comment by haoshuai714** [comment]
pip install av2

**Comment by handsomeZhuang** [comment]
> pip install av2
