### ISSUE TITLE
Only LiDAR Code

### ISSUE THREAD

**Issue by Ricky-Developer** [hustvl/MapTR#76]
Hi, Thank you very much for your outstanding work. Is it possible to open-source the code for the LiDAR branch? Your efforts in this area would be greatly appreciated.

**Comment by outsidercsy** [comment]
LiDAR-only MapTR can be modified from multi-modal MapTR.  Please try it.

> Hi, Thank you very much for your outstanding work. Is it possible to open-source the code for the LiDAR branch? Your efforts in this area would be greatly appreciated.

**Comment by outsidercsy** [comment]
> I have the same wish that the code for the offline LiDAR method VMA will be opened source. Thanks a lot.

We are heavily involved in some other works. The code of VMA may be released a few months later.
