### ISSUE TITLE
How did nd-to-end Planning come about?

### ISSUE THREAD

**Issue by PlutoXN** [hustvl/MapTR#79]
How did the content in the nd-to-end Planning video come about? Which model do I need to use?

**Comment by PlutoXN** [comment]
> 如何形象化它？python tools/maptr/vis_pred.py /path/to/experiment/config /path/to/experiment/ckpt 中的config和ckpt是训练后生成的吗？是否已有训练完成结果文件？

**Comment by outsidercsy** [comment]
It’s about another work https://github.com/hustvl/VAD,  which extends MapTR to an end-to-end planning framework.
