### ISSUE TITLE
Issues relating to topicality

### ISSUE THREAD

**Issue by PlutoXN** [hustvl/MapTR#80]
Hello, is it possible to convert the input camera into a map in real time like yolo? Do you need to train it every time before visualizing it? How to reproduce what is in this video of End-to-end Planning? Is it possible to delete the number of cameras?

**Comment by LegendBC** [comment]
> Is it possible to convert the input camera into a map in real time like yolo? 

MapTR already demonstrated much higher efficiency compared to prior arts. For even higher efficiency like YOLO (note that YOLO is used on single-camera setting), you can reduce the size of  input 6 camera images.

> Do you need to train it every time before visualizing it?
No, we don't. The trained models are ready for direct applications just like YOLO.

> How to reproduce what is in this video of End-to-end Planning? 
Please refer to [VAD](https://github.com/hustvl/VAD)

> Is it possible to delete the number of cameras?
Yes, MapTR is flexible to the number of cameras.
