### ISSUE TITLE
Any plan of releasing the code of MapTR-v2?

### ISSUE THREAD

**Issue by TonyXuQAQ** [hustvl/MapTR#81]
Hi, great work and thanks for sharing the code. is there any plan of releasing the code of maptr-v2 that was just published on arxiv? Since v2 is released, we are considering directly following v2 instead of v1. And we will cite both papers. Thanks in advance for your help.

**Comment by LegendBC** [comment]
Hi @TonyXuQAQ, thanks for your interest! We plan to release the code this month. Thank you for considering citing our papers in your future work.
