### ISSUE TITLE
Av2 data curruption

### ISSUE THREAD

**Issue by imyyf** [hustvl/MapTR#83]
https://github.com/hustvl/MapTR/blob/11307ed835dd7534ebb8927df9609f0b1b825aa6/projects/mmdet3d_plugin/datasets/av2_map_dataset.py#L1202
https://github.com/hustvl/MapTR/blob/11307ed835dd7534ebb8927df9609f0b1b825aa6/projects/mmdet3d_plugin/datasets/av2_map_dataset.py#L1203
https://github.com/hustvl/MapTR/blob/11307ed835dd7534ebb8927df9609f0b1b825aa6/projects/mmdet3d_plugin/datasets/av2_map_dataset.py#L1203
Have you met Av2 data curruption? We meet the image data is none or the lidar data is none. In our Av2 data, there are 4% val data are curruption. Does it influence the evaluation rationality？

**Comment by LegendBC** [comment]
All models are evaluated under the same evaluation data. Though there exists currupted data, we don't think it will affect the fariness of the valuation. The only incurred issue is that it will decrease the samples for evaluation, but AV2 data frequency is much higher than nuScenes (10Hz vs 2Hz). In conclusion, we don't think it will influence the evaluation rationality.

**Comment by imyyf** [comment]
Thanks for your reply
