### ISSUE TITLE
Code releasing

### ISSUE THREAD

**Issue by TonyXuQAQ** [hustvl/MapTR#87]
Hi, may I know when will the code be available? Since our team is on a project and plans to base it on powerful MapTR-v2 instead of MapTR-v1. Thanks for your consideration.

**Comment by LegendBC** [comment]
I have sent it to your email, please check it out. Thanks for your interest in MapTRv2.

**Comment by TonyXuQAQ** [comment]
Thanks for your prompt response and help!

**Comment by EnternalTwinkle** [comment]
> Hi @TonyXuQAQ , since we add many features in MapTRv2, the code is under heavy reconstruction. For your convenience, I will send you our local code with corresponding training instructions through email.

thanks for ur great work.  our team is also very interested in Maptrv2. my email 1017094591@qq.com. thanks a lot！
