### ISSUE TITLE
MapTRv2 code realese?

### ISSUE THREAD

**Issue by EnternalTwinkle** [hustvl/MapTR#89]
Hi, may I know when will the MapTRv2 code be available? my email 1017094591@qq.com. Thanks for your consideration.

**Comment by EnternalTwinkle** [comment]
@LegendBC

**Comment by LegendBC** [comment]
Thanks for your interest, we have released initial MapTRv2 at [maptrv2](https://github.com/hustvl/MapTR/tree/maptrv2) branch.
