### ISSUE TITLE
Is any positional encoding used in the hierarchical query embedding scheme?

### ISSUE THREAD

**Issue by SiuTo** [hustvl/MapTR#9]
Hi, thanks for your excellent work!
I have a question about the hierarchical query embedding. Is any positional encoding used? If it is used, how is it used?

**Comment by LegendBC** [comment]
Thanks for your interest! We release an initial version of MapTR, you can refer to the [code ](https://github.com/hustvl/MapTR/blob/main/projects/mmdet3d_plugin/maptr/dense_heads/maptr_head.py#L221-L224)
