### ISSUE TITLE
Question about multi_shifts_pts_tensor

### ISSUE THREAD

**Issue by Watebear** [hustvl/MapTR#91]
May I ask a question about variable: multi_shifts_pts_tensor.
It's shape is [num_samples, num_final_shift_num, fixed_num, 2], in practice [n, 19, 20, 2]。
In dimension 1， 19 is consists of 3 parts：（1）1 is coordinate points of line，（2）1 is coordinate points of line in reverse order，（3）other 17 are padding values with -1。
Why is it designed like this？

**Comment by LinaShanghaitech** [comment]
> May I ask a question about variable: multi_shifts_pts_tensor. It's shape is [num_samples, num_final_shift_num, fixed_num, 2], in practice [n, 19, 20, 2]。 In dimension 1， 19 is consists of 3 parts：（1）1 is coordinate points of line，（2）1 is coordinate points of line in reverse order，（3）other 17 are padding values with -1。 Why is it designed like this？

I think the author wants to align the different numbers of permutations between Polyline and Polygon, which you can check **Figure.3** in the paper. Polyline only has two permutations, so it is needed to pad with an invalid value (-10000).

**Comment by Watebear** [comment]
> t

Thanks！
