### ISSUE TITLE
is CustomAV2OfflineLocalMapDataset  missing?

### ISSUE THREAD

**Issue by yqj20020174** [hustvl/MapTR#92]
I am reading the MapTRV2。In configs/maptrv2/maptrv2_av2_3d_r50_6ep_w_centerline.py, dataset_type is "CustomAV2OfflineLocalMapDataset"。But，I can not find the implementation  in mmdet3d_plugin/datasets.
Is there some difference compared to CustomAV2LocalMapDataset？

**Comment by LegendBC** [comment]
Thanks for pointing it out. I just uploaded  av2_offlinemap_dataset.py, please check it out in our latest commitment.
