### ISSUE TITLE
[maptrv2 branch] CustomAV2OfflineLocalMapDataset is missing

### ISSUE THREAD

**Issue by gold-mango** [hustvl/MapTR#95]
Hi，

I can't find the dataset file that contains CustomAV2OfflineLocalMapDataset class.

**Comment by yqj20020174** [comment]
The author had unloaded. You need to the newest code.

**Comment by LegendBC** [comment]
Please refer to the latest code and we have uploaded the corresponding ckpt &log on argoverse2 dataset
