### ISSUE TITLE
'MapTRv2' and 'CustomNuScenesOfflineLocalMapDataset' in MapTRv2

### ISSUE THREAD

**Issue by sjtuxcx** [hustvl/MapTR#96]
Hi, thank you for your inspiring work! When I run the MapTRv2 code, I found the error of "KeyError: 'MapTRv2 is not in the models registry'" and "KeyError: 'CustomNuScenesOfflineLocalMapDataset is not in the dataset registry'". Are there some files missing?

**Comment by LegendBC** [comment]
You can use our latest code and checkout to ***maptrv2*** branch. You can find the `CustomNuScenesOfflineLocalMapDataset` class [here](https://github.com/hustvl/MapTR/blob/maptrv2/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py#L1023)
